### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by UnexMC** [room17/SkyBlock#49]
What about:

- A SkyBlock Ore Generator

When you are invited, and accept it then theres no message like "You've join %players% Isle"

**Comment by GiantQuartz** [comment]
What do you mean with "SkyBlock Ore Generator"?

**Comment by JOrlex** [comment]
the skyblock random ore gen is a plugin on poggit, but its in dev, and no one can look at it, but that would be a very useful plugin

**Comment by JOrlex** [comment]
skyblock random ore gen means, when u make a cobblegen, instead of just cobble, u get other ores aswell

**Comment by UnexMC** [comment]
yes
