### ISSUE TITLE
break/place blocks

### ISSUE THREAD

**Issue by JOrlex** [room17/SkyBlock#50]
the plugin works, but once you join your is, you cant place or break blocks, and ik for sure it has nothing to do with me because there is no spawn protection and im not op

**Comment by GiantQuartz** [comment]
I can't reproduce this issue — Are you completely sure you disabled spawn protection? Can anyone else confirm this issue?

**Comment by JOrlex** [comment]
yes i can completly confirm that, i even had a my computer on to make sure

**Comment by JOrlex** [comment]
do u need proof? i can get it

**Comment by JOrlex** [comment]
you might wanna make permissions and set them to true, like an is perm that allows you to break/plac eand is always true
