### ISSUE TITLE
Clear/restore inventory.

### ISSUE THREAD

**Issue by jackthehack21** [room17/SkyBlock#52]
Hi I love your plugin it’s the first successful generator for skyblock I found compatible with 3.0.0 but I do have one problem:
When you go to your island you keep your inventory, and vice verse leaving the island.
Could you add another file in resources that holds everyone’s inventory so when they join they swap it out for their skyblock inventory so you can’t bring/take any items to/from your island.

**Comment by GiantQuartz** [comment]
Sounds like a good idea!

**Comment by jackthehack21** [comment]
Only as in my server people are taking a lot of items there so that would help

**Comment by GiantQuartz** [comment]
I like the idea, but some people may refuse it.

**Comment by thisIsHexmor** [comment]
add a selection in config for that
i really need it too
it's my problem too
