### ISSUE TITLE
World generation issues.

### ISSUE THREAD

**Issue by Ben420** [room17/SkyBlock#64]
> Fatal error: Declaration of SkyBlock\generator\generators\BasicIsland::__construct(pocketmine\level\ChunkManager $level, $seed, array $options = Array) must be compatible with pocketmine\level\generator\Generator::__construct(array $settings = Array) in /plugins/SkyBlock-master/src/SkyBlock/generator/generators/BasicIsland.php on line 26

So yeah... Also there is a problem with your private functions such as onEnable and onDisable. They need to be public.

**Comment by GiantQuartz** [comment]
You're using PocketMine 3.0.0. 
Do not download the source from GitHub, instead, get an older version compatible with 3.0.0 from our Poggi.

**Comment by Ben420** [comment]
What server software should we use that's compatible?
