### ISSUE TITLE
The Skyblock core crashes the server

### ISSUE THREAD

**Issue by RedCraftGH** [room17/SkyBlock#67]
Fatal error: Declaration of SkyBlock\generator\generators\BasicIsland::__construct(pocketmine\level\ChunkManager $level, $seed, array $options = Array) must be compatible with pocketmine\level\generator\Generator::__construct(array $settings = Array) in /plugins/SkyBlock-master/src/SkyBlock/generator/generators/BasicIsland.php on line 26

The plugin crashes the entire server when it is loaded.

**Comment by GiantQuartz** [comment]
**This plugin is written for PocketMine 4.0.0**
