### ISSUE TITLE
Hot Suggestions

### ISSUE THREAD

**Issue by Shelly7w7** [room17/SkyBlock#74]
1. Add /is top to show islands with big amount of blocks placed.
2. Add /is upgrade which upgrades your island manually with money deduction but on diff blocks milestone.
3. Add blocks milestone messages like, when u place 10000 blocks, a broadcast is and saying "Player's Island reached a milestone of 10000 blocks"
4. Add another rank called "Leader".

Sorry for bad English, its because i type carelessly and fast on my pc keyboard without seeing it lol.

hopefully some or all will be implemented ;D

**Comment by GiantQuartz** [comment]
Upgrade was mentioned in #69 and we already have a rank named like that. However, everything else could be added to the core! Thanks for your suggestions.

**Comment by Shelly7w7** [comment]
Np!

**Comment by AyzrixYTB** [comment]
/is top is really a good idea :D.
