### ISSUE TITLE
Blocks bug

### ISSUE THREAD

**Issue by Shelly7w7** [room17/SkyBlock#77]
If you make a farm, e.g melon, your isle blocks get reduced. Like if a melon grows or we harvest it, the blocks will decrease.

**Comment by Shelly7w7** [comment]
Fix itttt xd

**Comment by GiantQuartz** [comment]
ab90923a484fa80c7a42730e429c3a0e620ca876 fixes this, crops are no longer recognized as a size-incrementing factor.

**Comment by Shelly7w7** [comment]
Still is happening, is it bc im using old config files?
