### ISSUE TITLE
Players can’t use their own island

### ISSUE THREAD

**Issue by RyanTheOwner** [room17/SkyBlock#80]
I had one of my staff members create an island and they couldn’t destroy anything or use their island at all, but only I could since I am oped

**Comment by AlexPads** [comment]
Have you tried Turning off Spawn Protection in your Server.properties File? That happened to me once :)

**Comment by xDanub** [comment]
I am having the same issue, I have turned Spawn protection to 1, 0, and -1, and tried, but each time to no avail. I have no idea how to fix and would like some help. ¯\_(ツ)_/¯

**Comment by GiantQuartz** [comment]
@xDanub Which version of PocketMine and SkyBlock are you using? Does this happen to all the players? What steps to do you follow to produce this behaviour?

**Comment by xDanub** [comment]
I am using
`Pocketmine 3.3.2`
-`Skyblock 2.1.2`

This only happenes to players who are NOT opped. I can break blocks when I am opped, but when I deop I cannot.

Steps to reproduce:
Install olugin
/is create
/is join
/deop (if necessary)
Break blocks.
Noted that when deopped you can still open the chest!
I also sent you a friend request on discord if you would like to get on and try yourself on my server (Danub#0318) 
Thanks! :)

**Comment by GiantQuartz** [comment]
@RyanTheOwner @xDanub Apparently, some external plugins don't let SkyBlock work correctly. If you are using _Festival_, go to config.yml and set Edit to false
