### ISSUE TITLE
Plugin does not work properly

### ISSUE THREAD

**Issue by Xenophilicy** [room17/SkyBlock#82]
Hello developers from **room17**! I have just downloaded your plugin _'SkyBlock'_ and have run into an issue along the way of using it.

Not too sure what is going on really, I downloaded the latest from [Poggit](https://poggit.pmmp.io/p/SkyBlock/2.1.2) _(Version 2.1.2 as of November 16, 2018)_ as a .phar and simply put it into the plugins folder, in my directory for the server. 

### First Error
The error I see when I try to use the plugin _(for example "/island")_ is:
```
[23:14:59] [Server thread/CRITICAL]: Unhandled exception executing command 'is' in isle: Call to a member function sendTranslatedMessage() on null
[23:14:59] [Server thread/CRITICAL]: Error: "Call to a member function sendTranslatedMessage() on null" (EXCEPTION) in "SkyBlock.phar/src/room17/SkyBlock/command/IsleCommandMap" at line 140
```
![error-1](https://user-images.githubusercontent.com/44390060/48657659-092f7100-e9fa-11e8-91a5-ea97d59c8903.png)

### Second Error
The second error that I noticed was when any player was to type a string into chat such as "Hello!", it would throw out this error:
```
[23:15:48] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerChatEvent' to 'SkyBlock v2.1.2': Call to a member function hasIsle() on null on room17\SkyBlock\SkyBlockListener
[23:15:48] [Server thread/CRITICAL]: Error: "Call to a member function hasIsle() on null" (EXCEPTION) in "SkyBlock.phar/src/room17/SkyBlock/SkyBlockListener" at line 142
```
![error-2](https://user-images.githubusercontent.com/44390060/48657663-1ba9aa80-e9fa-11e8-963b-d72a7c3c4807.png)

For me, to recreate this error, all I simply did was download it and place it into my plugins folder, as I stated above. Although I am having errors, I can see that many others have gotten it to perform correctly. Maybe a compatibility issue? No idea. But I do look forward to using this plugin for my server in the future because it looks to be very well made. 

If you need the server directory entirely, just let me know, and I can gladly send it to you! 

Thanks so much for your time!

- Xenophilicy (Owner of XenoServers)
- Discord **Xenophilicy#8252**

**Comment by GiantQuartz** [comment]
I am trying to reproduce this issue, which version of PocketMine were you running when this happened?

**Comment by GiantQuartz** [comment]
(I closed this issue because I couldn't reproduce it)

**Comment by Xenophilicy** [comment]
No problem, I got it working just fine, would you be alright.if I forked this and made a few changes to customize stuff for my server? If not that's totally ok. Just checking with you guys first. Thanks!!

**Comment by GiantQuartz** [comment]
@Xenophilicy as long as it respect our license, you can do whatever you want with this plugin

**Comment by Xenophilicy** [comment]
Thanks, no problem!
