### ISSUE TITLE
Suggestions : 

### ISSUE THREAD

**Issue by LeoBdt** [room17/SkyBlock#86]
Hello, i've many suggestions...

First, can you add a no-void system ? 
Second, can you add a way to stack spawners on themself (64x spawner on one) 
And third, can you add an easier way to edit the isles generation? 

thanks.

**Comment by GiantQuartz** [comment]
1. I assume you are talking about a method to prevent players from falling to the void. I am going to add an option to enable that feature soon.
2. The milestone of this plugin is to bring a cool, user-friendly game mode. SkyBlock is not designed to bring extra functionality to servers other than the game mode itself.
3. You can create your own generator and them use `IsleGeneratorManager->registerGenerator()`, it is not difficult.
